apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-list-save-handler
    app: todo-list
  name: todo-list-save-handler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-list-save-handler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/todolist-k8s-specs-default: "true"
        io.kompose.service: todo-list-save-handler
    spec:
      containers:
        - image: thuzar115/todo-list-save-handler:1.0
          name: todo-list-save-handler
          resources: {}
          volumeMounts:
            - mountPath: "/app/config"
              name: appsettings
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: appsettings
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: todolist-keyvault
status: {}
